In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
books = pd.read_csv('../data/Books.csv')
users = pd.read_csv('../data/Users.csv')
ratings = pd.read_csv('../data/Ratings.csv')

C:\Users\chery\AppData\Local\Temp\ipykernel_17812\3334888019.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('../data/Books.csv')

In [7]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [11]:
books.info()

<class 'pandas.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  str
 1   Book-Title           271360 non-null  str
 2   Book-Author          271358 non-null  str
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  str
 5   Image-URL-S          271360 non-null  str
 6   Image-URL-M          271360 non-null  str
 7   Image-URL-L          271357 non-null  str
dtypes: object(1), str(7)
memory usage: 16.6+ MB

In [9]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [12]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  str
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 6.4 MB

In [10]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [14]:
books_genre = pd.read_csv('../data/BookCrossingThemes.csv',  sep=';')

In [15]:
books_genre.head()

,Book-Title,Book-Author,User-ID,ISBN,Book-Rating,Year-Of-Publication,Publisher,Location,Age,category,description,num_words,num_chars,cleaned_description,Theme
0,The Terminal Man,Michael Crichton,276964,345354621,10,1988,Ballantine Books,"villa ridge, missouri, usa",34.0,Fiction,Hearry Benson suffers from violent seizures. W...,54,335,hearry benson suffers violent seizure becomes ...,Psychological Thriller
1,The Chamber,John Grisham,276964,440220602,9,1995,Dell Publishing Company,"villa ridge, missouri, usa",34.0,American fiction,While the executioners prepare the gas chamber...,26,155,executioner prepare gas chamber protester gath...,Crime Thrillers and Detective Drama
2,The Girl Who Loved Tom Gordon : A Novel,Stephen King,276964,684867621,8,1999,Scribner,"villa ridge, missouri, usa",34.0,Fiction,A story of a nine year old who wanders off in ...,19,90,story nine year old wanders wilderness area he...,Spiritual and Self-Help
3,In the Dark,Richard Laymon,276964,843949163,8,2001,Leisure Books,"villa ridge, missouri, usa",34.0,California,A tale of suspense follows young librarian Jan...,44,250,tale suspense follows young librarian jane ker...,Vampire/Paranormal Fantasy
4,Tailchaser's Song,Tad Williams,276964,886773741,7,1994,Daw Books,"villa ridge, missouri, usa",34.0,Fiction,"Fritti Tailchaser, a ginger tomcat of courage ...",31,199,fritti tailchaser ginger tomcat courage curios...,Cozy Mysteries

In [21]:
# 1. Unique User-IDs in books_genre
unique_users_rated = books_genre['User-ID'].nunique()
print(f"Unique Users in ratings: {unique_users_rated}")

# 2. Check for missing users 
missing = books_genre[~books_genre['User-ID'].isin(users['User-ID'])]
print(f"User-IDs in ratings NOT in users table: {missing['User-ID'].nunique()}")

# 3. Unique themes count
print(f"Unique Themes: {books_genre['Theme'].nunique()}")
# print(books_genre['Theme'].value_counts().head(25)) # Top 10 genres

# 3. Unique category count
print(f"Unique Categories: {books_genre['category'].nunique()}")
print(books_genre['category'].value_counts().head(10)) # Top 10 genres

Unique Users in ratings: 5424
User-IDs in ratings NOT in users table: 0
Unique Themes: 25
Unique Categories: 471
category
Fiction                      46728
Juvenile Fiction              2834
Biography & Autobiography     2428
['Fiction']                   1744
Humor                          735
American fiction               701
Bildungsromans                 363
Business & Economics           346
Family & Relationships         328
Adventure stories              307
Name: count, dtype: int64

In [19]:
books_genre.info()

<class 'pandas.DataFrame'>
RangeIndex: 70622 entries, 0 to 70621
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Book-Title           70622 non-null  str
 1   Book-Author          70622 non-null  str
 2   User-ID              70622 non-null  int64
 3   ISBN                 70622 non-null  str
 4   Book-Rating          70622 non-null  int64
 5   Year-Of-Publication  70622 non-null  int64
 6   Publisher            70622 non-null  str
 7   Location             70622 non-null  str
 8   Age                  52393 non-null  float64
 9   category             67538 non-null  str
 10  description          70622 non-null  str
 11  num_words            70622 non-null  int64
 12  num_chars            70622 non-null  int64
 13  cleaned_description  70622 non-null  str
 14  Theme                70622 non-null  str
dtypes: float64(1), int64(5), str(9)
memory usage: 8.1 MB