Exercise 1

Task: Write a short essay on the following: what is data analysis, wht is it important in modern contexts, and list and describe three areas where data analysis is applied today.

Data analysis is the process of collecting data, cleansing the data to ensure quality and reliability, exploring the data to identify patterns, anomalies, or relationships among different variables, interpreting and drawing conclusions from the data, presenting the data visually, and reporting your findings to stakeholders. It's used in many facets of modern life today - from busienss strategy decision making, scientific research, and aiding in public policy formation.

Exercises 2
**bold text**
Task: for the following dataset : [How Much Sleep Do Americans Really Get?](https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D2%20-%20Data%20U.%20and%20pre-processing/How%20Much%20Sleep%20Do%20Americans.zip), [Global Trends in Mental Health Disorder](https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D2%20-%20Data%20U.%20and%20pre-processing/Global%20Trends%20in%20Mental%20Health%20Disorder.zip) and [Credit Card Approvals](https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D2%20-%20Data%20U.%20and%20pre-processing/Credit%20Card%20Approvals%20(Clean%20Data).zip).

Load the dataset into Jupyter or Google Colab.
Display the first few rows.
Provide a brief dataset description.

**Exercise 3**

For the datasets from the previous exercise, categorize each column of it as either quantitative or qualitative and explain your reasoning.

In [2]:
import pandas as pd

In [7]:
pd.read_csv("Time Americans Spend Sleeping.csv")

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both
...,...,...,...,...,...,...,...,...,...
940,940,2013,Annual,8.83,0.085,Nonholiday weekdays,65 years and over,Sleeping,Women
941,941,2014,Annual,8.98,0.086,Nonholiday weekdays,65 years and over,Sleeping,Women
942,942,2015,Annual,8.83,0.074,Nonholiday weekdays,65 years and over,Sleeping,Women
943,943,2016,Annual,8.92,0.071,Nonholiday weekdays,65 years and over,Sleeping,Women
944,944,2017,Annual,8.81,0.091,Nonholiday weekdays,65 years and over,Sleeping,Women

In [9]:
american_sleep = pd.read_csv("Time Americans Spend Sleeping.csv")

In [10]:
american_sleep.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

**Exercise 2**

The dataset describes the time Americans spent sleeping each night, in an annual period. Each row is a year. The data looks at avg hrs per day sleeping and includes the standard deviation for the data. Information on "type of days" was included, so the data can be looked at as a whole (all days) or in groups, such as non-holday weekdays to see differences in sleep patterns. It's also divided into age group, and sex.

**Exercise 3: Data Classification**

*    year: qualitative, ordinal
*    period: qualitative, nominal
*    avg hrs per day sleeping: quantitative, continuous
*    standard error: quantitative, continuous
*    type of days: qualitative, nominal
*    age group: qualitative, ordinal
*    activity: qualitative, nominal
*    sex: qualitative, nominal

In [11]:
mental_health = pd.read_csv("Mental health Depression disorder Data.csv")

C:\Users\chery\AppData\Local\Temp\ipykernel_30428\2644170009.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  mental_health = pd.read_csv("Mental health Depression disorder Data.csv")

In [12]:
mental_health.head()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

**Exercise 2**

The mental health depression disorder data looks at a global analysis of different mental health diseases per year in various countries.

**Exercise 3: Data Classification**

*    Entity: qualitative, nominal
*    Code: qualitative, nominal
*    Year: qualitative, ordinal
*    Schizophrenia (%): quantitative, continuous
*    Bipolar (%): quantitative, continuous
*    Eating disorders (%): quantitative, continuous
*    Anxiety (%): quantitative, continuous
*    Drug use (%): quantitative, continuous
*    Depression (%): quantitative, continuous
*    Alcohol use (%): quantitative, continuous

In [13]:
cc_approvals = pd.read_csv("clean_dataset.csv")

In [14]:
cc_approvals.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

**Exercise 2**

Credit Card approval data looks at a list of individuals. For each individual, they are classified by different data points. Much of the data is classified as either 0 or 1, such as gender, marriage status, if they're a customer, prior default history, employment status, and if they have a drivers license. Other data includes their age, their debt, number of years employed, citizenship status, zip code, income, and finally if they are approved.

**Exercise 3**

*    Gender: qualitative, nominal
*    Age: quantitative, continuous
*    Debt: quantitative, continuous
*    Married: qualitative, nominal
*    Bank Customer: qualitative, nominal
*    Industry: qualitative, nominal
*    Ethnicity: qualitative, nominal
*    years employed: quantitative, continuous
*    prior default (assuming the 0/1 represents yes or no): qualitative, nominal
*    Employed:qualitative, nominal
*    Credit Score: quantitative, ordinal
*    Drivers license: qualitative, nominal
*    Citizen: qualitative, nominal
*    Zip code: qualitative, nominal
*    income: quantitative, continous
*    Approved: qualitative, nominal

**Exercise 4**

Load the Iris dataset using Kaggle into a Jupyter Notebook or Google Colaboratory Notebook.
Identify and list which columns in your dataset are qualitative and which are quantitative.
Write a brief description of why each column is classified as qualitative or quantitative.

In [15]:
iris = pd.read_csv("Iris.csv")

In [16]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

**Exercise 4**

quantitative, continuous. They are numbers that can be averaged and are non-discrete
*   Sepal Length CM
*   Sepal Width CM
*   Petal Length CM
*   Petal Width CM


*   Species: qualitative, nominal. Not numbers and no one species is greater than another

**Exercise 5**

* Load the How Much Sleep Do Americans Really Get? dataset into Jupyter or Google Colab.
* Identify columns that could be interesting for a specific type of analysis (e.g., trend analysis, group comparison) and explain your choice.
* Tools: Jupyter Notebook, Python with Pandas library.

**Exercise 5**

* year: analyze how sleep habits have changed over time
* type of days: comparison tables, comparing weekends to weekdays etc
* Age group: comparison of different age groups sleeing habits. Can also combine with different age groups over different days
* sex: comparison between men and women

**Exercise 6**

Below are various data sources. Identify whether each one is an example of structured or unstructured data.

* A company’s financial reports stored in an Excel file. - structured data
* Photographs uploaded to a social media platform. - unstructured
* A collection of news articles on a website. - unstructured
* Inventory data in a relational database. - structured
* Recorded interviews from a market research study. - unstructured

**Exercise 7**

For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

* A series of blog posts about travel experiences.- tag each post with country, topic, count number of impressions and likes. Track these metrics.
* Audio recordings of customer service calls. - measure length of the call and if the caller calls back or not. Also can start by asking the customer to select what issue they are calling about so the calls can start to be classified into specific buckets.
* Handwritten notes from a brainstorming session. - find key words from the notes and pull out topics
* A video tutorial on cooking. - track ingredient list, time to prep / cook, number of likes on the video.

**Exercise 8**

Import the train dataset. Use the train.csv file.
Print the first few rows of the DataFrame.

In [17]:
train = pd.read_csv("train.csv")

In [18]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Exercise 9**

* Create a simple dataframe.
* Export the dataframe to an excel file.
* Export the dataframe to a JSON file.

In [19]:
data = {
    "city": ["Paris", "Paris", "Paris", "Paris",
             "London", "London", "London", "London",
             "Rome", "Rome", "Rome", "Rome"],
    "year": [2001, 2008, 2009, 2010,
             2001, 2006, 2011, 2015,
             2001, 2006, 2009, 2012],
    "pop": [2.148, 2.211, 2.234, 2.244,
            7.322, 7.657, 8.174, 8.615,
           2.547, 2.627, 2.734, 2.627]
}

In [20]:
census = pd.DataFrame(data)

In [21]:
# Save to the Colab session storage
census.to_excel('census_data.xlsx', index=False)

In [22]:
# 'records' format is usually the most common (list of dictionaries)
census.to_json('census_data.json', orient='records', indent=4)

**Exercise 10**

* Import the JSON data from the provided URL.
* Use Pandas to read the JSON data.
* Display the first five entries of the data.

In [23]:
posts = pd.read_json("posts.json")

In [ ]:
posts.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

: